dev_directory : ./dev_data
eval_directory : ./eval_data
model_directory: 
  baseline: ./model
  idcae: ./model_idcae
result_directory:
  baseline: ./result
  idcae: ./result_idcae
result_file: result.csv

max_fpr : 0.1

feature:
  baseline:
    n_mels: 128
    frames : 5
    n_fft: 1024
    hop_length: 512
    power: 2.0
  idcae:
    n_mels: 128
    frames: 5
    n_fft: 1024
    hop_length: 512
    power: 2.0

train_param:
  ToyCar:
    encoder: 
      lr: 0.000003
    decoder:
      lr: 0.001
      gamma: 0.9
  fan:
    encoder:
      lr: 0.000001
    decoder:
      lr: 0.0003
      gamma: 0.9
  slider:
    encoder:
      lr: 0.000001
    decoder:
      lr: 0.0005
      gamma: 0.9
  pump: 
    encoder:
      lr: 0.000001
    decoder:
      lr: 0.001
      gamma: 0.8

fit:
  baseline:
    epochs : 100
    batch_size : 512
    validation_split : 0.1
  idcae:
    epochs: 100
    batch_size: 512
    validation_split: 0.1